### ISSUE TITLE
"Hide Products" No Longer Working in Google Chrome

### ISSUE THREAD

**Issue by ourichermath** [SteamDatabase/BrowserExtension#25]
Summary:  In Steam Database's options, I've got "Hide products on sales page that you are not interested in" checked.  But, products I've checked as "Not Interested" on Steam are not being hidden on SteamDB's Sales page.

Apology:  I'd initially commented on this in a closed Issue:

https://github.com/SteamDatabase/BrowserExtension/issues/9#issuecomment-413020884

But, since it's continuing, I thought it would be best if I started my own, open issue.  Sorry.

Details:  I'm using:
- Steam Database version 1.8.3 from the Chrome Web Store ( https://chrome.google.com/webstore/detail/steam-database/kdbmhfkmnlmbkgbabkdealhhbfhlmmon )
- Google Chrome version 69.0.3497.32 (Official Build) beta (64-bit)
- Windows 10 Pro x64
- I'm logged into SteamDB with my Steam credentials
- I'm logged into Steam in my browser
- I'm allowing cookies but blocking 3rd party cookies. However, I've got store.steampowered.com on my cookie whitelist.

As of about 4 days ago, I'm pretty sure this was working.  It looked like new games that I marked as "Not Interested" would disappear from the Sale page within a few hours. But, since then, things I mark as "Not Interested" are no longer being removed from the SteamDB Sales page. Even if I force a re-sync via the SteamDB Settings page, nothing changes. Ditto for forcing a refresh on the page with variations of F5 or CTRL+R.  Turning the option off and on again makes no difference.  Turning the extension, itself, off and on makes no difference.

In my browser, if I look at the store pages for the items I've marked as "Not Interested," they are actually showing as "Not Interested." Ditto for doing that within Steam, itself. Going to:

https://store.steampowered.com/account/notinterested/

shows what appears to be my up-to-date list of "Not Interested" games (75 of them).

If I check my cookies and site data in Chrome and limit them to those with "steam" in them, there are two with local data:  steamdb.info and store.steampowered.com.  The local data under the steamdb.info one seems to be getting modified (current last date/time is when I started checking this stuff today).  But, the local data under the store.steampowered.com one hasn't been modified in 11 days.

I don't know if any of that makes any difference, but those are the only things I can think of to give you to help you track this down.

**Comment by xPaw** [comment]
Can you try now? I pushed a fix on the site.

**Comment by ourichermath** [comment]
Still doesn't seem to be working.  The SteamDB Sales page is now telling me:

"You are not logged in on Steam Store.  Make sure third-party cookies for "store.steampowered.com" are enabled."

But, browsing over to store.steampowered.com shows me as signed in.  As a note, Chrome doesn't have an option (that I can find) for white-listing third-party cookies.  There is an option to white-list cookies (set to allow store.steampowered.com) which I assume will white-list ALL the cookies from store.steampowered.com (even third-party ones).

In my browser, I've logged out of Steam and re-logged in.  I've also re-entered my profile under SteamDB Calculator, re-synced via SteamDB's Settings, and logged out of SteamDB (including deleting my SteamDB profile) and then logged back in.  "Not Interested" items are still showing under SteamDB's Sales.

**Comment by xPaw** [comment]
There's a cookie icon in the address bar when cookies are blocked. this isn't an issue with steamdb.

**Comment by ourichermath** [comment]
Thanks.  That bit about the cookie icon helped me track it down (though I didn't see a cookie icon in the address bar). The problem was with the EFF's "Privacy Badger."  On the SteamDB Sale page, it showed one item being blocked.  It was the cookie from store.steampowered.com.  I whitelisted it there and everything works.  Sorry about that.
